### ISSUE TITLE
Push to pypi

### ISSUE THREAD

**Issue by tvwenger** [LucaCappelletti94/pygifsicle#11]
The version on pypi is still failing for python 3.8 because https://github.com/LucaCappelletti94/pygifsicle/pull/10 hasn't been pushed.

**Comment by LucaCappelletti94** [comment]
Eta 10min

**Comment by LucaCappelletti94** [comment]
Pushed to Pypi, do let me know if stuff now works :)

**Comment by tvwenger** [comment]
It works. Thanks!
