### ISSUE TITLE
1.0.6 ModuleNotFoundError: No module named 'IPython'

### ISSUE THREAD

**Issue by aurivus-ph** [LucaCappelletti94/pygifsicle#13]
### Issue
Importing the pygifsicle module after installation yields the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../.venv/lib/python3.9/site-packages/pygifsicle/__init__.py", line 4, in <module>
    support_luca("pygifsicle")
  File ".../.venv/lib/python3.9/site-packages/support_developer/luca.py", line 9, in support_luca
    support_message(
  File ".../.venv/lib/python3.9/site-packages/support_developer/support_message.py", line 49, in support_message
    from IPython.display import HTML, display
ModuleNotFoundError: No module named 'IPython'
```
This only happens in version 1.0.6. Version 1.0.5 is not affected.

### Steps for Reproduction
```bash
# set up a fresh virtual environment and install pygifsicle
python3 -m venv .venv 
. .venv/bin/activate
pip install pygifsicle

# try to import pygifsicle
python3 -c 'import pygifsicle'

# ERROR!
```

### Suggested Solution
IPython is required for this module, and should not become a dependency.
I recommend skipping the support developer if it is not installed.

**Comment by LucaCappelletti94** [comment]
Hello! [Support developer](https://github.com/LucaCappelletti94/support_developer) is another (recent) package of mine that I created to let developers advertise their GitHub support a tad more.

I **DEFINITELY** need to fix corner cases such as this one, though I thought I had wrapped that in a `ModuleNotFoundError ` try/except. Possibly I forgot to publish it to PyPi.

**Comment by FFSchier** [comment]
Hi Luca, a push would be greatly appreciated for non-.ipynb usage 👍🏽 Great work!

**Comment by LucaCappelletti94** [comment]
@Glokta0  ETA 1 hour, save for more explosions

**Comment by LucaCappelletti94** [comment]
Ok, it should work properly now (version `1.0.7`), please do let me know. [If my work saved you enough time, please, do consider supporting the development of this and other libraries I work on ❤️](https://github.com/sponsors/LucaCappelletti94)

**Comment by aurivus-ph** [comment]
Thanks, this works fine!
