### ISSUE TITLE
please remove begging ware

### ISSUE THREAD

**Issue by cjw296** [LucaCappelletti94/pygifsicle#14]
There's nothing that's likely to make me someone sponsor someone less than an unwanted pop-up add appearing in a  jupyter notebook from a library :-(

**Comment by LucaCappelletti94** [comment]
I am gradually removing those things, though I believe they were an important social experiment. Millions of downloads of my packages and no supporters suggest open source is not the correct way to go to pay rent and get coffee.

**Comment by LucaCappelletti94** [comment]
Done

**Comment by cjw296** [comment]
Speaking from personal experience of developing open source software for 25 years, building a living off donations is unlikely to work. Popular projects are great for mentioning during job interviews and project pitches, especially if the employer or customer uses those projects. The other option that can work is "fremium", where you have an open source project with an paid-for option that includes support/deployment/hosting or (and I've seen this fail miserably) extra features.

Donations/sponsorship/tidelift/etc may work for a bit of extra money on the side, but I would never recommend it as a way to pay the rent.

**Comment by LucaCappelletti94** [comment]
Again, as mentioned earlier, it was an experiment I wanted to do to see whether this would work at all. With the download metrics, I was able to put a percentage of supporters over the number of downloads, and the result has been about 3 euros for about 2 million downloads across the different packages. I agree that these things do not pay at all, but now I also have numbers to back this claim.
