### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by mluerig** [LucaCappelletti94/pygifsicle#2]
I keep getting  `FileNotFoundError: [WinError 2] The system cannot find the file specified`

any idea why? the file _definetely_ exists

```
gifsicle("E:\\Python\\crawler\\no_sync\\sat.gif", optimize=True)
Traceback (most recent call last):

  File "<ipython-input-28-68c10b72d05d>", line 1, in <module>
    gifsicle("E:\\Python\\crawler\\no_sync\\sat.gif", optimize=True)

  File "C:\Anaconda3\envs\pp37\lib\site-packages\pygifsicle\pygifsicle.py", line 53, in gifsicle
    str(colors), "--output", destination])

  File "C:\Anaconda3\envs\pp37\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:

  File "C:\Anaconda3\envs\pp37\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Anaconda3\envs\pp37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)

  File "C:\Anaconda3\envs\pp37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by LucaCappelletti94** [comment]
Could you please add a minimal example to reproduce the issue? Thanks!

**Comment by LucaCappelletti94** [comment]
Moreover, the issue is not with the gif image but with the installation of gifsicle, since the error comes from [this line](https://github.com/LucaCappelletti94/pygifsicle/blob/fdfd2820b284790cd083772f5114c6de3cf8bdd9/pygifsicle/pygifsicle.py#L52). What happens if you run `gifsicle` in your terminal?

**Comment by mluerig** [comment]
sorry I'm dumb, gifsicle wasn't in the environmental variables - working fine!

**Comment by LucaCappelletti94** [comment]
No problem, I'll add this to the troubleshooting section of the readme. 

If you face any other issue do let me know!

**Comment by AlexKalopsia** [comment]
Hi @mluerig , I am having the same exact problem. I've tried adding `c:\users\alex\appdata\local\programs\python\python38\lib\site-packages\pygifsicle` to my user Environment Variables but I still get the error. Any idea how to fix this? 

If I do `pip install pygifsicle` it says it's already installed. but if I try and do `gifsicle` from terminal it says it doesn't know the command

**Comment by mluerig** [comment]
pygifsicle are just bindings for gifsicle, you still need to install the library. e.g. for windows, look here https://eternallybored.org/misc/gifsicle/, and add those to the path
