### ISSUE TITLE
Tha gif output size is greater than the input

### ISSUE THREAD

**Issue by leo-smi** [LucaCappelletti94/pygifsicle#4]
I put as input an 12MB gif image and the output was a 29MB gif, what's the problem?

**Comment by LucaCappelletti94** [comment]
Hello Leo,

This is a simple python wrapper of [gifsicle](https://github.com/kohler/gifsicle), that only makes it easy to use the gifsicle library from python.

For any software bugs relative to the [gifsicle](https://github.com/kohler/gifsicle) library I suggest you open up an issue in their repository.

Good luck,
Luca
