### ISSUE TITLE
Optimize gif cannot find specified file path

### ISSUE THREAD

**Issue by ChinCity** [LucaCappelletti94/pygifsicle#6]
I'm trying to optimize a gif, but the debugger returns a FileNotFoundError. Which is strange because I can see the gif in file explorer.

Error: 

    Exception has occurred: FileNotFoundError
    [WinError 2] The system cannot find the file specified
    File "C:\Users\[]\gif-mov\gif-maker.py", line 61, in <module>
        optimize(gif_path)

Code: 

    import os
    import re
    from typing import Iterator, List

    import imageio
    from pygifsicle import optimize
   
    def sort_iter(filepaths: List[str]) -> Iterator[str]:
    """order files from 1 to 9"""

    if __name__ == '__main__': 
    folder = os.path.join('D:\\', 'Documents', 'Gif')
    gif_path = os.path.join(folder, 'test.gif')

    # Get a list of filepaths for the images
    image_filepaths = glob.glob(os.path.join(folder, 'img*.jpg'))

    print(image_filepaths)
    print(folder)
   
    # Sort, read and store images in sequence
    images = []
    seconds = []

    for path in sort_iter(image_filepaths):
        images.append(imageio.imread(path))
        seconds.append(1)

    print(images)

    imageio.mimsave(gif_path, images, duration=seconds)

    optimize(gif_path)

**Comment by LucaCappelletti94** [comment]
Hello @ChinCity, could you share the complete traceback?

Also, would it be possible to provide a minimal example that reproduces this error? For instance, if you simply run optimize on a gif that you know exists instead of creating one, does it work?

I can check if there is something I can do on the python bindings part of gifsicle, but it is also likely it is something related to using the [gifsicle library itself on Windows](https://github.com/kohler/gifsicle).

**Comment by ChinCity** [comment]
Hey @LucaCappelletti94,

Traceback (most recent call last):

    File "gif-maker.py", line 61, in <module>
     optimize(gif_path)
    File "C:\Users\[]\AppData\Local\Programs\Python\Python38\lib\site-packages\pygifsicle\pygifsicle.py", line 64, in optimize
    gifsicle(source, *args, **kwargs, optimize=True)
    File "C:\Users\\AppData\Local\Programs\Python\Python38\lib\site-packages\pygifsicle\pygifsicle.py", line 52, in gifsicle
    subprocess.call(["gifsicle", *options, *sources, "--colors",
    File "C:\Users\[]\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
    File "C:\Users\[]\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\[]\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified


I also made a shorter script with an existing gif, just a few lines: 

    import os
    from pygifsicle import optimize

    folder = os.path.join('D:\\', 'Document', 'Gif')
    gif_path = os.path.join(folder, 'test.gif')
    optimize(gif_path)

and i got a similar traceback error: 

    File "optimize.py", line 7, in <module>
    optimize(gif_path)
    File "C:\Users\[]\AppData\Local\Programs\Python\Python38\lib\site-packages\pygifsicle\pygifsicle.py", line 64, in optimize
    gifsicle(source, *args, **kwargs, optimize=True)
    File "C:\Users\[]\AppData\Local\Programs\Python\Python38\lib\site-packages\pygifsicle\pygifsicle.py", line 52, in gifsicle
    subprocess.call(["gifsicle", *options, *sources, "--colors",
    File "C:\Users\[]\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
    File "C:\Users\[]\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\[]\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified

Should I follow instructions to build gifscale on windows? From the link you provided?

**Comment by LucaCappelletti94** [comment]
The complete error tells you that it is not failing at finding the image path, but the gifsicle executable. As [stated in the readme](https://github.com/LucaCappelletti94/pygifsicle#troubleshooting), it is likely you haven't installed gifiscle properly in your windows system.

I will add an exception in the python wrapper that notifies this case more clearly in windows systems. 

In the other OS it is automatically installed, but on Windows it is not possible.

**Comment by ChinCity** [comment]
Interesting, I need to make a switch to linux asap!

I downloaded the ports from the link https://eternallybored.org/misc/gifsicle/ however I'm not sure how I install them? The instructions aren't clear. I tried double clicking the applications in the image below but nothing happens. 

![image](https://user-images.githubusercontent.com/37304682/102101582-b87de280-3e22-11eb-8977-eb82bc6fa5b0.png)

**Comment by LucaCappelletti94** [comment]
You need to put that wherever you have your system executables defined from the PATH on your system.

**Comment by LucaCappelletti94** [comment]
I have updated the exceptions so that this kind of installation error is easier to understand and fix.
